services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        fromEnvVar: N8N_USER
      - key: N8N_BASIC_AUTH_PASSWORD
        fromEnvVar: N8N_PASSWORD
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n.onrender.com
